### ISSUE TITLE
How to stop terracord from announcing reconnections in Discord?

### ISSUE THREAD

**Issue by avizmarlon** [FragLand/terracord#106]
Every now and then, the following error happens:
![image](https://user-images.githubusercontent.com/24354489/94624330-91d0f680-028c-11eb-98a2-aba59bb09a63.png)

When this happens, the bot reconnects and announces "Relay available" on discord. 
![image](https://user-images.githubusercontent.com/24354489/94624457-e70d0800-028c-11eb-9455-fc805e8429d5.png)

 It happens kinda often, so it's annoying for the members of the discord.

I checked the discord.cs file and it says something about announcing only if configured to do so. How do I configure it to NOT announce it?

**Comment by ldilley** [comment]
Greetings, @avizmarlon.

Disabling the following option in `terracord.xml` will do what you want:

```xml
  <!-- Notify Discord channel of relay availability after restoring the connection -->
  <announce reconnect="true" />
```

**Comment by ldilley** [comment]
This issue has been resolved via Discord. The user was provided with a current `Terracord.dll` based on the latest source (f034948) (file attached within the `#terracord` text channel). The user was also advised to use the latest `terracord.xml` which contains the `announce reconnect` option.

**Comment by OhZedTee** [comment]
I used the above configuration, yet I still get the reconnect annoucement. I enabled debug and see that the announce variable is not being picked up. In fact, I copy and pasted the config file straight from the repo and updated the value to false, yet it still doesn't work. Help? @ldilley

**Comment by ldilley** [comment]
@OhZedTee: You need to be using Terracord built from commit >= 9ad999a (6/8/2020 or later). The release zip archive for Terracord 1.2.0 was released just over a week prior (on 5/30/2020) to when this particular feature was added. I was not planning to release 1.2.1 until TShock 4.4.0 is out of the pre-release phase.

Let me know if you are unable to build your own Terracord DLL and I will supply a recent build here as an attachment.

**Comment by OhZedTee** [comment]
Hi @ldilley, I don't exactly have the environment set up to build the DLL. Are you able to send me the DLL if it's not too much trouble? That would be great! Otherwise, I'll wait for the proper release of Terracord 1.2.1

**Comment by ldilley** [comment]
No worries, @OhZedTee. The attached zip file contains a `Terracord.dll` based off the latest commit, f034948, at the time of this writing. It should work fine with any existing dependencies. Don't forget to use the latest [terracord.xml](https://github.com/FragLand/terracord/blob/master/terracord.xml). Please let me know how it goes.

📎 [Terracord-f034948.zip](https://github.com/FragLand/terracord/files/5412455/Terracord-f034948.zip)

**Comment by OhZedTee** [comment]
Thank you @ldilley, appreciate the help.
